config/routes.rb
Pdfv5Admin::Application.routes.draw do
  root :to => "jobs#monitor"
  resources :jobs do
    resources :histories
    collection do 
      get 'monitor'
    end
  end
  
  resources :histories do
    resources :logs
  end
  

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :job
  has_many :logs
end

app/models/history_observer.rb
class HistoryObserver < ActiveRecord::Observer
  def after_update(history)
    #if history.result.eql? "failure"
      #Rails.logger.info "job 처리실패 : #{history.job.name}"
      #job 실패
    #end
    
    #gap = history.start_at.to_time - history.finish_at.to_time 
    #if(gap > history.job.schedule_min * 60)
      #Rails.logger.info "job 처리지연: #{history.job.name}"
    #end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :histories
  validates :name, :presence => true
end

app/models/job_cron.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class JobCron
  include CronEdit
    
  def initialize
    #Rails.logger.info "[cronjob] initializing for #{APP_CONFIG['crontab_user']}"
    #@crontab = Crontab.new APP_CONFIG['crontab_user']
  end

  def create(job)  
    Crontab.Add job.name, "#{schedule(job)} #{command(job)}" if job.active?
    #create_ntx(job)
    #@crontab.commit
  end
  
  def create_ntx(job)
    Rails.logger.info "[cronjob] creating #{job.name}, schedule => #{schedule(job)}, command => #{command(job)}"
    @crontab.add job.name, "#{schedule(job)} #{command(job)}" if job.active?
  end
  
  def destroy(job)
    Crontab.Remove job.name
    #destroy_ntx job
    #@crontab.commit
  end
  
  def destroy_ntx(job)
    Rails.logger.info "[cronjob] deleting #{job.name}"
    @crontab.remove job.name
  end
  
  def replace(as_is, to_be)
    destroy(as_is)
    create(to_be)
    #destroy_ntx(as_is)
    #create_ntx(to_be)
    #@crontab.commit
  end
  
 
  def schedule(job)
    job.schedule
  end

  def command(job)
    "#{Rails.root}/lib/runner/job_runner #{APP_CONFIG['rest_server']} #{job.id} #{job.jar_path} #{job.arguments}" 
  end
end

app/models/job_monitor.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class JobMonitor
  attr_accessor :job_name, :last_history
  def initialize(&block)
    yield self
  end
end

app/models/job_observer.rb
class JobObserver < ActiveRecord::Observer
  def after_create(job)
    JobCron.new.create(job)
  end
  
  def before_update(job)
    @job_was = Job.find(job)
    @job_now = job
  end
  
  def after_update(job)
    JobCron.new.replace(@job_was, @job_now)
  end
  
  def after_destroy(job)
    JobCron.new.destroy(job)
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :history
end

app/models/log_observer.rb
class LogObserver < ActiveRecord::Observer
  def after_create(log)
    if log.log_type.eql? "error"
      #Rails.logger.info "job 처리 중 오류 발생: #{log.history.job.name}"
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  # GET /jobs/:job_id/histories
  def index
    @job = Job.find(params[:job_id])
    @histories = @job.histories.find(:all, :limit => 20, :order => "id DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @histories }
    end
  end
  
  # POST /jobs/:job_id/histories.json
  def create
    @job = Job.find(params[:job_id])
    @history = @job.histories.build(params[:history])

    respond_to do |format|
      if @history.save
        format.json { render json: @history, status: :created }
      else
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/:job_id/histories/:id.json
  def update
    @job = Job.find(params[:job_id])
    @history = @job.histories.find(params[:id])

    respond_to do |format|
      if @history.update_attributes(params[:history])
        format.json { head :no_content }
      else
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
  
  # GET /jobs/monitor
  def monitor
    @monitors = []
    Job.all.each do |job|
      @monitors << JobMonitor.new { |monitor|
        monitor.job_name =job.name
        monitor.last_history = job.histories.last
      }
    end
    @monitors
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /histories/:history_id/logs
  # GET /histories/:history_id/logs.json
  def index
    @logs = History.find(params[:history_id]).logs.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end
  
  # POST /histories/:history_id/logs.json
  def create
    @history = History.find(params[:history_id])
    @log = @history.logs.build(params[:log])
    
    respond_to do |format|
      if @log.save
        format.json { render json: @log, status: :created}
      else
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def monitor_status(monitor)
    return "unknown" if monitor.nil?
    return "never started" if monitor.last_history.nil? 
  
    status? monitor.last_history
  end
  
  def monitor_started(monitor)
    return "unknown" if monitor.nil?
    return "" if monitor.last_history.nil?
    return "" if monitor.last_history.start_at.nil?

    monitor.last_history.start_at.to_formatted_s(:kor_long)
  end
  
  def monitor_pinged(monitor)
    return "unknown" if monitor.nil?
    return "" if monitor.last_history.nil?
    return "" if monitor.last_history.last_ack_at.nil?
    monitor.last_history.last_ack_at.to_formatted_s(:kor_long)
  end
  
  def monitor_finished(monitor)
    return "unknown" if monitor.nil?
    return "" if monitor.last_history.nil?
    return "" if monitor.last_history.finish_at.nil?
    monitor.last_history.finish_at.to_formatted_s(:kor_long)
  end
  
  def monitor_result(monitor)
    return "unknown" if monitor.nil?
    return "" if monitor.last_history.nil?
    monitor.last_history.result
  end
  
  def monitor_logs_url(monitor)
    return "" if monitor.nil? or monitor.last_history.nil?
    history_logs_url(monitor.last_history)
  end
  
  def status?(history)
    if history.start_at.nil? && history.finish_at.nil?
      "starting"
    elsif history.start_at && history.finish_at.nil?
      "running"
    elsif history.start_at && history.finish_at
      "done"
    else
      "unknown"
    end
  end
  
  def runjars
    Dir["#{APP_CONFIG['jar_base']}/**/*.jar"]      
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/histories/index.html.erb
<h1>Histories</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
    <th>Job</th>
    <th>Started at</th>
    <th>Last Ack at</th>
    <th>Finished at</th>
    <th>result</th>
  </tr>
  </thead>
  <tbody>
  <% @histories.each do |history| -%>
   <tr>
    <td><%= history.id %></td>
    <td><%= history.job.name %></td>
    <td><%= history.start_at.to_formatted_s(:kor_long) unless history.start_at.nil? %></td>
    <td><%= history.last_ack_at.to_formatted_s(:kor_long) unless history.last_ack_at.nil? %></td>
    <td><%= history.finish_at.to_formatted_s(:kor_long) unless history.finish_at.nil? %></td>
    <td><%=  link_to  "#{history.result}", history_logs_url(history)%></td>
   </tr>
  <% end -%>
  </tbody>
</table>

app/views/jobs/_form.html.erb
<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.job.name", :default => "Name"), :class => :label %>
  <div class="input">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :active, t("activerecord.attributes.job.active", :default => "Active"), :class => :label %>
  <div class="input">
    <%= f.check_box :active, :class => 'check_box' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :jar_path, :class => :label %>
  <div class="input">
    <%= f.select(:jar_path, runjars) %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :arguments, t("activerecord.attributes.job.arguments", :default => "Arguments"), :class => :label %>
  <div class="input">
    <%= f.text_field :arguments, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :schedule, t("activerecord.attributes.job.schedule", :default => "Schedule"), :class => :label %>
  <div class="input">
    <%= f.text_field :schedule, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :description, t("activerecord.attributes.job.description", :default => "Description"), :class => :label %>
  <div class="input">
    <%= f.text_area :description, :class => 'text_area' %>
  </div>
</div>

<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", jobs_path %>
</div>

app/views/jobs/edit.html.erb
<%= form_for @job, :url => job_path(@job), :html => { :class => "edit_job", :id => "edit_job" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.job.name", :default => t("activerecord.labels.name", :default => "Name")) %>
    </th>
    <th>Created at</th>
    <th>Active</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs.each do |job| -%>
   <tr>
    <td><%= job.id %></td>
        <td><%= link_to job.name, job_path(job) %>
    </td>
    <td><%= job.created_at %></td>
    <td><%= job.active? %></td>
    <td>
      <%= link_to "Run Now!", job_path(job), :method => :run, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-success' %>	
      <%= link_to "Show", job_path(job), :class=> 'btn'%>
      <%= link_to "Edit", edit_job_path(job), :class => 'btn btn-inverse'%>
      <%= link_to "Destroy", job_path(job), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger' %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_job_path, :class => 'btn btn-primary' %>

app/views/jobs/monitor.html.erb
<h1>Job monitoring dashboard</h1>
<script>
  setInterval(function(){
    window.location = window.location;
  },60000)
</script>
<div align="right">
  refresh at : <%= Time.current.to_formatted_s(:kor_long)  %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Job Name</th>
      <th>Status</th>
      <th>Start</th>
      <th>Last Ping</th>
      <th>Finish</th>
      <th>Result</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @monitors.each do |monitor| %>
    <tr>
      <td><%= monitor.job_name %></td>
      <td><%= monitor_status(monitor)%></td>
      <td><%= monitor_started(monitor) %></td>
      <td><%= monitor_pinged(monitor) %></td>
      <td><%= monitor_finished(monitor) %></td>
      <td><%= link_to "#{monitor_result(monitor)}", monitor_logs_url(monitor) %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<%= form_for @job, :url => jobs_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/jobs/show.html.erb
<label class="label"><%= t("activerecord.attributes.job.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</label>
<p><%= @job.name %></p>

<label class="label"><%= t("activerecord.attributes.job.active", :default => t("activerecord.labels.active", :default => "Active")) %>:</label>
<p><%= @job.active %></p>

<label class="label"><%= t("activerecord.attributes.job.arguments", :default => t("activerecord.labels.arguments", :default => "Arguments")) %>:</label>
<p><%= @job.arguments %></p>

<label class="label"><%= t("activerecord.attributes.job.schedule", :default => t("activerecord.labels.schedule", :default => "Schedule")) %>:</label>
<p><%= @job.schedule %></p>

<label class="label"><%= t("activerecord.attributes.job.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</label>
<p><%= @job.description %></p>

<label class="label">jar path:</label>
<p><%= @job.jar_path %></p>

<label class="label"> 실행이력</label>
<p><%= link_to "보기", job_histories_url(@job) %>
<div class="form-actions">
<%= link_to "Back", jobs_path, :class => 'btn'  %>
<%= link_to "Edit", edit_job_path(@job), :class => 'btn' %>
<%= link_to "Delete", job_path(@job), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pdfv5Admin</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <!--link href="images/favicon.ico" rel="shortcut icon"-->
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="#">Pdfv5Admin</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Monitor", "/jobs/monitor"  %></li>
                <li><%= link_to "Job 관리", "/jobs"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                 <ul class="nav nav-list">
                    <li class="nav-header">Sidebar</li>
                    <li><%= link_to "coming soon", "/"  %></li>
                </ul>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy; TF4 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/logs/index.html.erb
<h1>Logs</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>Job</th>
    <th>Created at</th>
    <th>Type</th>
    <th>Message</th>
  </tr>
  </thead>
  <tbody>
  <% @logs.each do |log| -%>
   <tr>
    <td><%= log.history.job.name %></td>
    <td><%= log.created_at.to_formatted_s(:kor_long) %></td>
    <td><%= log.log_type %></td>
    <td><%= simple_format(log.message) %></td>
   </tr>
  <% end -%>
  </tbody>
</table>